id: ADD0D4A6A
base_file: fA625.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-11 13:40:07.735916
  last_modified_at: 2022-06-11 13:40:07.735922
